colorscheme badwolf

set nocompatible

filetype plugin on
syntax on

set tabstop=2
set softtabstop=2
set shiftwidth=2

set backspace=indent,eol,start

set expandtab
set number
set relativenumber

" Remap C-c to Esc to trigger InsertLeave
inoremap <C-c> <Esc>

augroup numbertoggle
  autocmd!
  autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
  autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
augroup END

set showcmd
set cursorline

set showmatch

set incsearch
set hlsearch

set smartindent
set autoindent

set splitright
set splitbelow

filetype indent on

noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

inoremap <Up> <NOP>
inoremap <Down> <NOP>
inoremap <Left> <NOP>
inoremap <Right> <NOP>

nnoremap <leader>ev :vsp $MYVIMRC<CR>
nnoremap <leader>sv :source $MYVIMRC<CR>

nnoremap <leader>t :call RunCurrentSpecFile()<CR>
nnoremap <leader>s :call RunNearestSpec()<CR>
nnoremap <leader>l :call runLastSpec()<CR>
nnoremap <leader>a :call RunAllSpecs()<CR>

let g:rspec_command = "Dispatch rspec {spec}"
let $FZF_DEFAULT_COMMAND = 'ag -g ""'

nnoremap <leader>; :AV<CR>

nnoremap <C-p> :Files<CR>
" remove trailing spaces on specific filetypes
autocmd FileType rake,slim,coffee,javascript,ruby,vue,sass,scss,yml,tf autocmd BufWritePre <buffer> %s/\s\+$//e

augroup filetypedetect
  au BufRead,BufNewFile *.axlsx setfiletype ruby
augroup END

set colorcolumn=80

set rtp+=/usr/local/opt/fzf
